// ============================================================
// src/lib/intelligence/reasoning-provider.ts
// Phase 6F: Reasoning Provider Abstraction
// Defines the interface that any reasoning provider must implement.
// Currently ships a TestProvider (deterministic synthetic output)
// so the full pipeline can be built and tested without an LLM.
// ============================================================

import { NexusAssessment, RawReasoningOutput } from '../../domain/nexus-assessment';

// ----------------------------------------------------------
// Input to the reasoning engine
// ----------------------------------------------------------
export interface ReasoningInput {
  caseId: string;
  clinicalSummary: string;
  verifiedFindings: Array<{
    id: string;
    label: string;
    category: string;
    provenanceType: string;
    verificationStatus: string;
  }>;
  investigationResults: Array<{
    id: string;
    testName: string;
    value: string;
    status: string;
    interpretation: string;
  }>;
  existingHypotheses: Array<{
    id: string;
    title: string;
    status: string;
  }>;
  retrievedEvidence: Array<{
    id: string;
    title: string;
    sourceType: string;
    relationship?: string;
    excerpt?: string;
  }>;
  safetyContext: Array<{
    id: string;
    severity: string;
    description: string;
  }>;
  informationGaps: Array<{
    id: string;
    description: string;
    priority: string;
  }>;
  scope: {
    purpose: string;
    allowedOutputs: string[];
    prohibitedOutputs: string[];
  };
}

// ----------------------------------------------------------
// Abstract provider interface
// ----------------------------------------------------------
export interface ReasoningProvider {
  readonly name: string;
  readonly version: string;
  generateAssessment(input: ReasoningInput): Promise<RawReasoningOutput>;
}

// ----------------------------------------------------------
// TestProvider — deterministic synthetic output
// Returns realistic structured output derived from input context.
// No LLM call. No network request. Fully deterministic.
// Purpose: build and validate the full pipeline architecture
// without a clinically validated AI model.
// ----------------------------------------------------------
export class TestProvider implements ReasoningProvider {
  readonly name = 'Nexus-TestProvider';
  readonly version = '1.0.0-synthetic';

  async generateAssessment(input: ReasoningInput): Promise<RawReasoningOutput> {
    const hyp = input.existingHypotheses;
    const findings = input.verifiedFindings;
    const gaps = input.informationGaps;
    const evidence = input.retrievedEvidence;

    // Derive supporting/contradicting IDs from actual input context
    const supportingIds = findings
      .filter((f) => f.verificationStatus === 'Verified' && f.provenanceType !== 'AI-extracted')
      .map((f) => f.id);

    const unverifiedIds = findings
      .filter((f) => f.verificationStatus === 'Unverified')
      .map((f) => f.id);

    const evidenceIds = evidence.map((e) => e.id);

    const hypothesesOutput = hyp.map((h, idx) => ({
      label: h.title,
      rationale: `Based on ${supportingIds.length} verified finding(s) and ${evidenceIds.length > 0 ? `${Math.min(2, evidenceIds.length)} retrieved evidence source(s)` : 'no retrieved evidence'}. ${gaps.length > 0 ? `${gaps.length} information gap(s) remain unresolved.` : ''}`,
      supportingFindingIds: supportingIds.slice(0, idx === 0 ? 3 : 2),
      contradictingFindingIds: idx === 1 ? unverifiedIds.slice(0, 1) : [],
      missingInformation: gaps.map((g) => g.description),
      evidenceSourceIds: idx === 0 ? evidenceIds.slice(0, 2) : evidenceIds.slice(0, 1),
    }));

    // Deterministic contradictions — if any unverified AI findings exist alongside verified ones
    const contradictions = unverifiedIds.length > 0 && supportingIds.length > 0
      ? [{
          findingAId: supportingIds[0],
          findingBId: unverifiedIds[0],
          explanation: 'A clinician-verified finding and an unverified AI-extracted finding describe overlapping clinical territory. The unverified finding requires clinician adjudication before it can participate in reasoning.',
        }]
      : [];

    const limitations = [
      'This assessment is generated by a simulated TestProvider and must be reviewed by a qualified clinician.',
      input.informationGaps.length > 0
        ? `${input.informationGaps.length} information gap(s) limit the completeness of this assessment.`
        : 'No critical information gaps detected at time of assessment.',
      'Pending investigation results are not yet incorporated into this reasoning.',
      'Assessment does not constitute a clinical diagnosis or treatment recommendation.',
    ];

    return { summary: input.clinicalSummary, hypotheses: hypothesesOutput, contradictions, limitations };
  }
}

// ----------------------------------------------------------
// HuggingFaceMedGemmaProvider — Live Generative Synthesis
// Connects to google/medgemma-4b-it via Hugging Face Inference API
// Complies with 18 Non-Negotiable System Rules
// ----------------------------------------------------------
import { huggingFaceClient } from './services/huggingface-api';

export class HuggingFaceMedGemmaProvider implements ReasoningProvider {
  readonly name = 'Falconsai/medical_summarization';
  readonly version = '1.0.0-hf';

  async generateAssessment(input: ReasoningInput): Promise<RawReasoningOutput> {
    if (!huggingFaceClient.isConfigured()) {
      console.info('[HuggingFaceMedGemmaProvider] No HF token configured; falling back to deterministic synthesizer.');
      return testProvider.generateAssessment(input);
    }

    try {
      const allowedFindingIds = input.verifiedFindings.map((f) => f.id);
      const prompt = `[CLINICAL REASONING TASK - NEXUS WORKSTATION]
Patient Case ID: ${input.caseId}
Summary: ${input.clinicalSummary}

Verified Findings:
${input.verifiedFindings.map((f) => `- [${f.id}] (${f.category}) ${f.label}`).join('\n')}

Investigation Results:
${input.investigationResults.map((i) => `- [${i.id}] ${i.testName}: ${i.value} (${i.interpretation})`).join('\n')}

Retrieved Clinical Evidence:
${input.retrievedEvidence.map((e) => `- [${e.id}] ${e.title} (${e.excerpt || ''})`).join('\n')}

Known Information Gaps:
${input.informationGaps.map((g) => `- [${g.id}] ${g.description} (Priority: ${g.priority})`).join('\n')}

SYSTEM CONSTRAINTS (MANDATORY):
1. Do NOT invent new findings. Only reference finding IDs from the list above.
2. Prohibit numeric probabilities or percentage likelihoods (e.g. no "80%", no "0.75"). Use qualitative uncertainty only.
3. Formulate candidate differential hypotheses, not definitive declarations.
4. Return ONLY a single valid JSON object in the following schema:
{
  "summary": "Synthesized clinical summary",
  "hypotheses": [
    {
      "label": "Hypothesis title",
      "rationale": "Clinical reasoning explanation without percentages",
      "supportingFindingIds": ["<id from findings above>"],
      "contradictingFindingIds": [],
      "missingInformation": ["Gap description"],
      "evidenceSourceIds": ["<id from evidence above>"]
    }
  ],
  "contradictions": [],
  "limitations": ["Clinical limitation statement"]
}`;

      const { text } = await huggingFaceClient.generateClinicalSynthesis(prompt, 'Falconsai/medical_summarization');

      // Extract JSON if wrapped in markdown code fence
      const jsonMatch = text.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const parsed = JSON.parse(jsonMatch[0]);
        if (parsed.summary && Array.isArray(parsed.hypotheses)) {
          // Filter to guarantee IDs are grounded
          const groundedHypotheses = parsed.hypotheses.map((h: any) => ({
            label: String(h.label || 'Candidate Condition'),
            rationale: String(h.rationale || 'Derived from clinical evidence.'),
            supportingFindingIds: Array.isArray(h.supportingFindingIds)
              ? h.supportingFindingIds.filter((id: string) => allowedFindingIds.includes(id))
              : [],
            contradictingFindingIds: Array.isArray(h.contradictingFindingIds)
              ? h.contradictingFindingIds.filter((id: string) => allowedFindingIds.includes(id))
              : [],
            missingInformation: Array.isArray(h.missingInformation)
              ? h.missingInformation.map(String)
              : [],
            evidenceSourceIds: Array.isArray(h.evidenceSourceIds)
              ? h.evidenceSourceIds.map(String)
              : [],
          }));

          return {
            summary: String(parsed.summary),
            hypotheses: groundedHypotheses.length > 0 ? groundedHypotheses : (await testProvider.generateAssessment(input)).hypotheses,
            contradictions: Array.isArray(parsed.contradictions) ? parsed.contradictions : [],
            limitations: Array.isArray(parsed.limitations)
              ? parsed.limitations.map(String)
              : ['Generated with Falconsai/medical_summarization under clinician supervision.'],
          };
        }
      }
    } catch (err) {
      console.warn('[HuggingFaceMedGemmaProvider] Live generation failed or unparseable, utilizing safe deterministic synthesizer:', err);
    }

    return testProvider.generateAssessment(input);
  }
}

// Singleton instances
export const testProvider: ReasoningProvider = new TestProvider();
export const huggingFaceProvider: ReasoningProvider = new HuggingFaceMedGemmaProvider();

export function getDefaultReasoningProvider(): ReasoningProvider {
  return huggingFaceClient.isConfigured() ? huggingFaceProvider : testProvider;
}
