// ============================================================
// src/lib/intelligence/reasoning-provider.ts
// Phase 6F: Reasoning Provider Abstraction
// Defines the interface that any reasoning provider must implement.
// Currently ships a TestProvider (deterministic synthetic output)
// so the full pipeline can be built and tested without an LLM.
// ============================================================

import { NexusAssessment, RawReasoningOutput } from '../../domain/nexus-assessment';

// ----------------------------------------------------------
// Input to the reasoning engine
// ----------------------------------------------------------
export interface ReasoningInput {
  caseId: string;
  clinicalSummary: string;
  verifiedFindings: Array<{
    id: string;
    label: string;
    category: string;
    provenanceType: string;
    verificationStatus: string;
  }>;
  investigationResults: Array<{
    id: string;
    testName: string;
    value: string;
    status: string;
    interpretation: string;
  }>;
  existingHypotheses: Array<{
    id: string;
    title: string;
    status: string;
  }>;
  retrievedEvidence: Array<{
    id: string;
    title: string;
    sourceType: string;
    relationship?: string;
    excerpt?: string;
  }>;
  safetyContext: Array<{
    id: string;
    severity: string;
    description: string;
  }>;
  informationGaps: Array<{
    id: string;
    description: string;
    priority: string;
  }>;
  scope: {
    purpose: string;
    allowedOutputs: string[];
    prohibitedOutputs: string[];
  };
}

// ----------------------------------------------------------
// Abstract provider interface
// ----------------------------------------------------------
export interface ReasoningProvider {
  readonly name: string;
  readonly version: string;
  generateAssessment(input: ReasoningInput): Promise<RawReasoningOutput>;
}

// ----------------------------------------------------------
// TestProvider — deterministic synthetic output
// Returns realistic structured output derived from input context.
// No LLM call. No network request. Fully deterministic.
// Purpose: build and validate the full pipeline architecture
// without a clinically validated AI model.
// ----------------------------------------------------------
export class TestProvider implements ReasoningProvider {
  readonly name = 'Nexus-TestProvider';
  readonly version = '1.0.0-synthetic';

  async generateAssessment(input: ReasoningInput): Promise<RawReasoningOutput> {
    const hyp = input.existingHypotheses;
    const findings = input.verifiedFindings;
    const gaps = input.informationGaps;
    const evidence = input.retrievedEvidence;

    // Derive supporting/contradicting IDs from actual input context
    const supportingIds = findings
      .filter((f) => f.verificationStatus === 'Verified' && f.provenanceType !== 'AI-extracted')
      .map((f) => f.id);

    const unverifiedIds = findings
      .filter((f) => f.verificationStatus === 'Unverified')
      .map((f) => f.id);

    const evidenceIds = evidence.map((e) => e.id);

    const hypothesesOutput = hyp.map((h, idx) => ({
      label: h.title,
      rationale: `Based on ${supportingIds.length} verified finding(s) and ${evidenceIds.length > 0 ? `${Math.min(2, evidenceIds.length)} retrieved evidence source(s)` : 'no retrieved evidence'}. ${gaps.length > 0 ? `${gaps.length} information gap(s) remain unresolved.` : ''}`,
      supportingFindingIds: supportingIds.slice(0, idx === 0 ? 3 : 2),
      contradictingFindingIds: idx === 1 ? unverifiedIds.slice(0, 1) : [],
      missingInformation: gaps.map((g) => g.description),
      evidenceSourceIds: idx === 0 ? evidenceIds.slice(0, 2) : evidenceIds.slice(0, 1),
    }));

    // Deterministic contradictions — if any unverified AI findings exist alongside verified ones
    const contradictions = unverifiedIds.length > 0 && supportingIds.length > 0
      ? [{
          findingAId: supportingIds[0],
          findingBId: unverifiedIds[0],
          explanation: 'A clinician-verified finding and an unverified AI-extracted finding describe overlapping clinical territory. The unverified finding requires clinician adjudication before it can participate in reasoning.',
        }]
      : [];

    const limitations = [
      'This assessment is generated by a simulated TestProvider and must be reviewed by a qualified clinician.',
      input.informationGaps.length > 0
        ? `${input.informationGaps.length} information gap(s) limit the completeness of this assessment.`
        : 'No critical information gaps detected at time of assessment.',
      'Pending investigation results are not yet incorporated into this reasoning.',
      'Assessment does not constitute a clinical diagnosis or treatment recommendation.',
    ];

    return { summary: input.clinicalSummary, hypotheses: hypothesesOutput, contradictions, limitations };
  }
}

// Singleton test provider instance
export const testProvider: ReasoningProvider = new TestProvider();
