-- ============================================================
-- 010_nexus_intelligence.sql
-- Nexus Clinical Intelligence tables: assessments, findings,
-- and recommendations.
-- No pseudo-certain numeric confidence (e.g. 0.94) is stored.
-- These are review items, not autonomous orders.
-- ============================================================

-- ----------------------------------------------------------
-- nexus_assessments
-- Structured synthesis created by Nexus intelligence service.
-- Status defaults to REVIEW_REQUIRED until signed off.
-- ----------------------------------------------------------
create table public.nexus_assessments (
  id                    uuid        primary key default gen_random_uuid(),
  case_id               uuid        not null references public.cases(id) on delete cascade,
  status                text        not null default 'REVIEW_REQUIRED',
  summary               text,
  data_completeness     text,
  evidence_consistency  text,
  applicability         text,
  limitations           text,
  model_name            text,
  model_version         text,
  created_at            timestamptz not null default now()
);

comment on table public.nexus_assessments is
  'Clinical intelligence assessment synthesis for a case. '
  'Contains qualitative appraisals (data completeness, consistency, limitations). '
  'Numeric certainty metrics are intentionally excluded.';

-- ----------------------------------------------------------
-- nexus_findings
-- Findings extracted or highlighted by Nexus requiring review.
-- ----------------------------------------------------------
create table public.nexus_findings (
  id            uuid        primary key default gen_random_uuid(),
  assessment_id uuid        not null references public.nexus_assessments(id) on delete cascade,
  finding_type  text        not null,              -- 'OBSERVATION', 'LAB_ANOMALY', 'RISK_FACTOR', etc.
  content       text        not null,
  status        text        not null default 'PENDING_REVIEW', -- 'PENDING_REVIEW', 'ACCEPTED', 'REJECTED', 'EDITED'
  created_at    timestamptz not null default now()
);

comment on table public.nexus_findings is
  'Atomic findings generated by Nexus requiring clinician verification.';

-- ----------------------------------------------------------
-- nexus_recommendations
-- Suggested next clinical steps or investigations to consider.
-- Non-autonomous advisory items only.
-- ----------------------------------------------------------
create table public.nexus_recommendations (
  id            uuid        primary key default gen_random_uuid(),
  assessment_id uuid        not null references public.nexus_assessments(id) on delete cascade,
  category      text,                              -- 'INVESTIGATION', 'MONITORING', 'SAFETY_CHECK'
  content       text        not null,
  rationale     text,
  status        text        not null default 'PENDING_REVIEW',
  created_at    timestamptz not null default now()
);

comment on table public.nexus_recommendations is
  'Decision support recommendations. Advisory only; never automatic clinical orders.';
