-- ============================================================
-- 035_remove_seeded_assessments.sql
-- Remove all seeded/hardcoded demo analysis data.
-- The Nexus analysis system now generates and persists
-- assessments dynamically when clinicians run analysis.
-- ============================================================

-- Remove seeded nexus findings (cascade from nexus_assessments)
-- and seeded nexus assessments for the demo case
delete from public.nexus_assessments
where id = '40000001-0000-0000-0000-000000000001';

-- Remove seeded hypotheses for the demo cases
-- (real hypotheses are generated by Nexus analysis runs)
delete from public.hypotheses
where id in (
  '30000001-0000-0000-0000-000000000001',
  '30000001-0000-0000-0000-000000000002',
  '30000001-0000-0000-0000-000000000003'
);

-- Remove seeded timeline event for Nexus synthesis
delete from public.timeline_events
where title = 'Nexus Clinical Synthesis generated'
  and actor_type = 'NEXUS_AI';
